"""initial schema

Revision ID: 21f7883d92fe
Revises:
Create Date: 2026-01-08 14:49:55.467931

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21f7883d92fe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("office", sa.Enum("H", "S", "P", name="office_enum"), nullable=False),
        sa.Column("party", sa.String(), nullable=True),
        sa.Column("party_full", sa.String(), nullable=True),
        sa.Column("state", sa.CHAR(length=2), nullable=False),
        sa.Column("district", sa.CHAR(length=2), nullable=True),
        sa.Column("incumbent_challenge", sa.CHAR(length=1), nullable=True),
        sa.Column("incumbent_challenge_full", sa.String(), nullable=True),
        sa.Column("candidate_status", sa.CHAR(length=1), nullable=True),
        sa.Column("active_through", sa.Integer(), nullable=True),
        sa.Column("cycles", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("election_years", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("federal_funds_flag", sa.Boolean(), nullable=True),
        sa.Column("has_raised_funds", sa.Boolean(), nullable=True),
        sa.Column("first_file_date", sa.Date(), nullable=True),
        sa.Column("last_f2_date", sa.Date(), nullable=True),
        sa.Column("last_file_date", sa.Date(), nullable=True),
        sa.Column("load_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_index(
        "idx_candidates_cycles",
        "candidates",
        ["cycles"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_candidates_state_office", "candidates", ["state", "office"], unique=False
    )
    op.create_table(
        "committees",
        sa.Column("committee_id", sa.String(), nullable=False),
        sa.Column("affiliated_committee_name", sa.String(), nullable=True),
        sa.Column("candidate_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "committee_type",
            sa.Enum(
                "C",
                "D",
                "E",
                "H",
                "I",
                "N",
                "O",
                "P",
                "Q",
                "S",
                "U",
                "V",
                "W",
                "X",
                "Y",
                "Z",
                name="committee_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("cycles", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("designation", sa.CHAR(length=1), nullable=True),
        sa.Column("designation_full", sa.String(), nullable=True),
        sa.Column("filing_frequency", sa.CHAR(length=1), nullable=True),
        sa.Column("first_f1_date", sa.Date(), nullable=True),
        sa.Column("first_file_date", sa.Date(), nullable=True),
        sa.Column("last_f1_date", sa.Date(), nullable=True),
        sa.Column("last_file_date", sa.Date(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("organization_type", sa.CHAR(length=1), nullable=True),
        sa.Column("organization_type_full", sa.String(), nullable=True),
        sa.Column("party", sa.String(), nullable=True),
        sa.Column("party_full", sa.String(), nullable=True),
        sa.Column("sponsor_candidate_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("state", sa.CHAR(length=2), nullable=True),
        sa.Column("treasurer_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("committee_id"),
    )
    op.create_table(
        "elections",
        sa.Column("election_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("office", sa.Enum("H", "S", "P", name="office_enum"), nullable=False),
        sa.Column("state", sa.CHAR(length=2), nullable=False),
        sa.Column("district", sa.CHAR(length=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("election_id"),
        sa.UniqueConstraint("cycle", "office", "state", "district"),
    )
    op.create_table(
        "election_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=True),
        sa.Column("candidate_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.ForeignKeyConstraint(
            ["election_id"],
            ["elections.election_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("election_id", "candidate_id"),
    )
    op.create_index(
        "idx_election_candidates_candidate_id",
        "election_candidates",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "schedule_e",
        sa.Column("sub_id", sa.String(), nullable=False),
        sa.Column("link_id", sa.BigInteger(), nullable=True),
        sa.Column("file_number", sa.Integer(), nullable=True),
        sa.Column("previous_file_number", sa.Integer(), nullable=True),
        sa.Column("candidate_id", sa.String(), nullable=True),
        sa.Column("committee_id", sa.String(), nullable=True),
        sa.Column(
            "support_oppose_indicator",
            sa.Enum("S", "O", name="support_oppose_enum"),
            nullable=True,
        ),
        sa.Column(
            "expenditure_amount",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("expenditure_date", sa.Date(), nullable=True),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("report_year", sa.Integer(), nullable=True),
        sa.Column("report_type", sa.String(), nullable=True),
        sa.Column("payee_name", sa.String(), nullable=True),
        sa.Column("expenditure_description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committees.committee_id"],
        ),
        sa.PrimaryKeyConstraint("sub_id"),
    )
    op.create_index(
        "idx_schedule_e_candidate_id", "schedule_e", ["candidate_id"], unique=False
    )
    op.create_index(
        "idx_schedule_e_committee_id", "schedule_e", ["committee_id"], unique=False
    )
    op.create_table(
        "totals_by_candidate",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.String(), nullable=True),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column(
            "support_oppose_indicator",
            sa.Enum("S", "O", name="support_oppose_enum"),
            nullable=True,
        ),
        sa.Column(
            "total",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "cycle", "support_oppose_indicator"),
    )
    op.create_table(
        "totals_by_election",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("election_id", sa.Integer(), nullable=True),
        sa.Column(
            "disbursements",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "independent_expenditures",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "receipts",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["election_id"],
            ["elections.election_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_totals_by_election_election_id",
        "totals_by_election",
        ["election_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Add trigger function for updated_at
    op.execute("""
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Add triggers to all tables
    tables = [
        "candidates",
        "committees",
        "elections",
        "election_candidates",
        "schedule_e",
        "totals_by_candidate",
        "totals_by_election",
    ]

    for table in tables:
        op.execute(f"""
            CREATE TRIGGER set_updated_at_{table}
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
        """)


def downgrade() -> None:
    """Downgrade schema."""

    # Drop triggers first
    tables = [
        "totals_by_election",
        "totals_by_candidate",
        "schedule_e",
        "election_candidates",
        "elections",
        "committees",
        "candidates",
    ]

    for table in tables:
        op.execute(f"DROP TRIGGER IF EXISTS set_updated_at_{table} ON {table}")

    # Drop function
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_totals_by_election_election_id", table_name="totals_by_election")
    op.drop_table("totals_by_election")
    op.drop_table("totals_by_candidate")
    op.drop_index("idx_schedule_e_committee_id", table_name="schedule_e")
    op.drop_index("idx_schedule_e_candidate_id", table_name="schedule_e")
    op.drop_table("schedule_e")
    op.drop_index(
        "idx_election_candidates_candidate_id", table_name="election_candidates"
    )
    op.drop_table("election_candidates")
    op.drop_table("elections")
    op.drop_table("committees")
    op.drop_index("idx_candidates_state_office", table_name="candidates")
    op.drop_index(
        "idx_candidates_cycles", table_name="candidates", postgresql_using="gin"
    )
    op.drop_table("candidates")
    # ### end Alembic commands ###
