"""add_committee_type_full

Revision ID: 6682f47f96e7
Revises: b3dc36a2bb53
Create Date: 2026-06-19 15:14:00.805033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6682f47f96e7'
down_revision: Union[str, Sequence[str], None] = 'b3dc36a2bb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committees', sa.Column('committee_type_full', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committees', 'committee_type_full')
    # ### end Alembic commands ###
