"""make office, committee type, state columns nullable

Revision ID: 712c11b94d85
Revises: ff298162850a
Create Date: 2026-02-04 18:17:52.486254

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "712c11b94d85"
down_revision: Union[str, Sequence[str], None] = "ff298162850a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidates",
        "office",
        existing_type=postgresql.ENUM("H", "S", "P", name="office_enum"),
        nullable=True,
    )
    op.alter_column(
        "candidates", "state", existing_type=sa.CHAR(length=2), nullable=True
    )
    op.alter_column(
        "committees",
        "committee_type",
        existing_type=postgresql.ENUM(
            "C",
            "D",
            "E",
            "H",
            "I",
            "N",
            "O",
            "P",
            "Q",
            "S",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
            name="committee_type_enum",
        ),
        nullable=True,
    )
    op.alter_column(
        "elections", "state", existing_type=sa.CHAR(length=2), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "elections", "state", existing_type=sa.CHAR(length=2), nullable=False
    )
    op.alter_column(
        "committees",
        "committee_type",
        existing_type=postgresql.ENUM(
            "C",
            "D",
            "E",
            "H",
            "I",
            "N",
            "O",
            "P",
            "Q",
            "S",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
            name="committee_type_enum",
        ),
        nullable=False,
    )
    op.alter_column(
        "candidates", "state", existing_type=sa.CHAR(length=2), nullable=False
    )
    op.alter_column(
        "candidates",
        "office",
        existing_type=postgresql.ENUM("H", "S", "P", name="office_enum"),
        nullable=False,
    )
    # ### end Alembic commands ###
