"""make_committee_type_nullable

Revision ID: 71c00547144a
Revises: 6682f47f96e7
Create Date: 2026-06-25 15:26:57.275447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71c00547144a'
down_revision: Union[str, Sequence[str], None] = '6682f47f96e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committees', 'committee_type',
               existing_type=postgresql.ENUM('C', 'D', 'E', 'H', 'I', 'N', 'O', 'P', 'Q', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z', name='committee_type_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committees', 'committee_type',
               existing_type=postgresql.ENUM('C', 'D', 'E', 'H', 'I', 'N', 'O', 'P', 'Q', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z', name='committee_type_enum'),
               nullable=False)
    # ### end Alembic commands ###
