"""add_candidate_inside_totals

Revision ID: 7e94b5f9c9c7
Revises: 71c00547144a
Create Date: 2026-06-30 12:00:31.881933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e94b5f9c9c7'
down_revision: Union[str, Sequence[str], None] = '71c00547144a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_inside_totals',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('receipts', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('disbursements', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('candidate_id', 'cycle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_inside_totals')
    # ### end Alembic commands ###
