"""add_schedule_e_totals_by_candidate

Revision ID: 8339719380a3
Revises: 7eedf72ae923
Create Date: 2026-07-06 14:55:46.224094

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8339719380a3"
down_revision: Union[str, Sequence[str], None] = "7eedf72ae923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    support_oppose_enum = postgresql.ENUM(
        "S", "O", name="support_oppose_enum", create_type=False
    )
    op.create_table(
        "schedule_e_totals_by_candidate",
        sa.Column("committee_id", sa.String(), nullable=False),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("support_oppose_indicator", support_oppose_enum, nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.candidate_id"]),
        sa.PrimaryKeyConstraint(
            "committee_id", "candidate_id", "cycle", "support_oppose_indicator"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_e_totals_by_candidate")
    # ### end Alembic commands ###
