"""add candidate_spending_totals

Revision ID: 8dec5034fb0f
Revises: 712c11b94d85
Create Date: 2026-03-04 15:21:58.297104

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dec5034fb0f"
down_revision: Union[str, Sequence[str], None] = "712c11b94d85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_spending_totals",
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("inside_receipts", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column(
            "inside_disbursements", sa.Numeric(precision=15, scale=2), nullable=True
        ),
        sa.Column("outside_support", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("outside_oppose", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("influence_ratio", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "vulnerability_factor", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.candidate_id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id", "cycle"),
    )
    # ### end Alembic commands ###

    op.execute("""
        CREATE TRIGGER set_updated_at_candidate_spending_totals
        BEFORE UPDATE ON candidate_spending_totals
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS set_updated_at_candidate_spending_totals ON candidate_spending_totals"
    )
    op.drop_table("candidate_spending_totals")
    # ### end Alembic commands ###
