"""remove_stale_tables

Revision ID: b3dc36a2bb53
Revises: 0c95890efc66
Create Date: 2026-06-16 16:37:14.900003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3dc36a2bb53'
down_revision: Union[str, Sequence[str], None] = '0c95890efc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop child tables before parents to respect FK constraints.
    op.drop_index(op.f('idx_schedule_e_candidate_id'), table_name='schedule_e')
    op.drop_index(op.f('idx_schedule_e_committee_id'), table_name='schedule_e')
    op.drop_table('schedule_e')
    op.drop_table('totals_by_candidate')
    op.drop_index(op.f('idx_election_candidates_candidate_id'), table_name='election_candidates')
    op.drop_table('election_candidates')
    op.drop_index(op.f('idx_totals_by_election_election_id'), table_name='totals_by_election')
    op.drop_table('totals_by_election')
    op.drop_table('elections')
    op.alter_column(
        'committees',
        'committee_type',
        existing_type=postgresql.ENUM(
            'C', 'D', 'E', 'H', 'I', 'N', 'O', 'P', 'Q', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z',
            name='committee_type_enum',
        ),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committees', 'committee_type',
               existing_type=postgresql.ENUM('C', 'D', 'E', 'H', 'I', 'N', 'O', 'P', 'Q', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z', name='committee_type_enum'),
               nullable=True)
    op.create_table('totals_by_election',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disbursements', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('independent_expenditures', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('receipts', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.election_id'], name=op.f('totals_by_election_election_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('totals_by_election_pkey'))
    )
    op.create_index(op.f('idx_totals_by_election_election_id'), 'totals_by_election', ['election_id'], unique=False)
    op.create_table('totals_by_candidate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cycle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('support_oppose_indicator', postgresql.ENUM('S', 'O', name='support_oppose_enum'), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], name=op.f('totals_by_candidate_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('totals_by_candidate_pkey')),
    sa.UniqueConstraint('candidate_id', 'cycle', 'support_oppose_indicator', name=op.f('totals_by_candidate_candidate_id_cycle_support_oppose_indic_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('election_candidates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], name=op.f('election_candidates_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['election_id'], ['elections.election_id'], name=op.f('election_candidates_election_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('election_candidates_pkey')),
    sa.UniqueConstraint('election_id', 'candidate_id', name=op.f('election_candidates_election_id_candidate_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_election_candidates_candidate_id'), 'election_candidates', ['candidate_id'], unique=False)
    op.create_table('elections',
    sa.Column('election_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cycle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('office', postgresql.ENUM('H', 'S', 'P', name='office_enum'), autoincrement=False, nullable=False),
    sa.Column('state', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('district', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('election_id', name=op.f('elections_pkey')),
    sa.UniqueConstraint('cycle', 'office', 'state', 'district', name=op.f('elections_cycle_office_state_district_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('schedule_e',
    sa.Column('sub_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('file_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_file_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('candidate_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('committee_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('support_oppose_indicator', postgresql.ENUM('S', 'O', name='support_oppose_enum'), autoincrement=False, nullable=True),
    sa.Column('expenditure_amount', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('expenditure_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('filing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('report_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payee_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expenditure_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], name=op.f('schedule_e_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.committee_id'], name=op.f('schedule_e_committee_id_fkey')),
    sa.PrimaryKeyConstraint('sub_id', name=op.f('schedule_e_pkey'))
    )
    op.create_index(op.f('idx_schedule_e_committee_id'), 'schedule_e', ['committee_id'], unique=False)
    op.create_index(op.f('idx_schedule_e_candidate_id'), 'schedule_e', ['candidate_id'], unique=False)
    # ### end Alembic commands ###
